### ISSUE TITLE
Non-ASCII character '\xe2' in file boing.py - including resolution

### ISSUE THREAD

**Issue by anothermouse** [Wireframe-Magazine/Code-the-Classics#2]
Code the Classics repository downloaded by:

git clone https://github.com/Wireframe-Magazine/Code-the-Classics.git

Attempting to run:
python3.7 ./boing.py
gives:
  File "boing.py", line 92
SyntaxError: Non-ASCII character '\xe2' in file boing.py on line 92

Also applies to line 120,206,247,251,277,330,331

This is due to whatever editor was used to edit the system creating an 'em' dash.  Replacing the extended - with a minus sign...or just deleting it resolves the problem. All of these error characters are in comments, so trivial to resolve. 

Python version 3.7.6 on an Ubuntu 18.04r2 system

**Comment by WillSams** [comment]
Seeing this in soccer.py as well.  I've created a pull request for changes to correct them in your branch.

**Comment by arganoid** [comment]
I have merged your pull request and fixed in other files too
