### ISSUE TITLE
PGZero 1.2.1 and Pygame 2 or higher do not recognise theme.ogg in music folder

### ISSUE THREAD

**Issue by DoctorMikeReddy** [Wireframe-Magazine/Code-the-Classics#6]
Not sure if this is a code-the-classics thing or a pgzero or pygame issue; have reported to the former. pygame 1.9.6 and pgzero 1.2 play the theme.ogg files, but upgrading either ( which requires the other to upgrade as well) breaks the theme sound, either with an error, or it just doesn't play. Re-encoding it does nothing

**Comment by DoctorMikeReddy** [comment]
Using python 3.8.10

**Comment by DoctorMikeReddy** [comment]
I have installed 3.8.6 on my Alienware and theme.ogg in the music folder works again. Must be an interaction between python 3.8.10 and Pygame 2.0.1

**Comment by arganoid** [comment]
See https://github.com/lordmauve/pgzero/issues/260

**Comment by arganoid** [comment]
I have pushed a fix for Boing so that menu sounds no longer crash the game if they are unable to play.
