### ISSUE TITLE
Missing a link and unexpected redirect. 

### ISSUE THREAD

**Issue by boggyuk** [Wireframe-Magazine/Code-the-Classics#8]
On:

1) https://www.raspberrypi.com/news/create-boing-our-python-tribute-to-pong/
and 
2) here in README.md there is a link (https://wireframe.raspberrypi.org/books/code-the-classics1) that mentions downloadable PDF; however, right now, both redirect to:

https://whynowgaming.com/

**Comment by bjepson** [comment]
Thanks, @boggyuk! I've set up a copy of the original page at https://magpi.raspberrypi.com/books/code-the-classics1 and updated both the blog post and the README for this repo.
